.PHONY: build run

build:
	@go build \
		-ldflags "-X main.version=$(shell git describe --tags --always --dirty 2>/dev/null || echo dev) \
				-X main.build=$(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)" \
		-o bin/{{.ProjectName}} ./cmd/app

run:
	@go run ./cmd/app

.DEFAULT_GOAL := run
